test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudflare:
  service: S3
  endpoint: https://<%= ENV['CLOUDFLARE_ACCOUNT_ID'] %>.r2.cloudflarestorage.com
  access_key_id: <%= ENV['CLOUDFLARE_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['CLOUDFLARE_ACCESS_SECRET'] %>
  region: auto
  bucket: <%= ENV['CLOUDFLARE_BUCKET'] %>
